version: '3.7'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      - dev-bashhistory:/commandhistory

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:homeassistant

    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    # environment:

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mqtt:
    image: eclipse-mosquitto:2.0.9
    restart: unless-stopped
    volumes:
      - mqtt-data:/mosquitto/data
      - ./helpers/mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: service:homeassistant
  homeassistant:
    image: homeassistant/home-assistant:2021.8
    restart: unless-stopped
    volumes:
      - ha-db:/config
      - ./helpers/homeassistant/configuration.yaml:/config/configuration.yaml
      - ./helpers/homeassistant/automations.yaml:/config/automations.yaml
      - ./helpers/homeassistant/groups.yaml:/config/groups.yaml
      - ./helpers/homeassistant/scenes.yaml:/config/scenes.yaml
      - ./helpers/homeassistant/scripts.yaml:/config/scripts.yaml
      - ./helpers/homeassistant/secrets.yaml:/config/secrets.yaml

volumes:
  mqtt-data:
  ha-db:
  dev-bashhistory:
